In [1]:
from Datos import Datos
from ValidacionSimple import ValidacionSimple
from ValidacionCruzada import ValidacionCruzada
from ValidacionBootstrap import ValidacionBootstrap
balloons = Datos('ConjuntosDatos/balloons.data')
tic_tac_toe = Datos('ConjuntosDatos/tic-tac-toe.data')
validacionSimple = ValidacionSimple(70)
validacionCruzada = ValidacionCruzada(6)
validacionBootstrap = ValidacionBootstrap()
validacionSimple.creaParticiones(balloons.datos)
validacionCruzada.creaParticiones(balloons.datos)
validacionBootstrap.creaParticiones(balloons.datos)

print("Simple", "Train:", validacionSimple.particiones[0].indicesTrain)
print("Simple", "Test:", validacionSimple.particiones[0].indicesTest)
# TODO: iterar para mostrar todas los folds cruzados
for particion in validacionCruzada.particiones:
    print("Cruzada", "Train:", particion.indicesTrain)
    print("Cruzada", "Test:", particion.indicesTest)
print("Boostrap", "Train:", validacionBootstrap.particiones[0].indicesTrain)
print("Boostrap", "Test:", validacionBootstrap.particiones[0].indicesTest)

# validacionBootstrap.creaParticiones(tic_tac_toe.datos)
# validacionCruzada.creaParticiones(tic_tac_toe.datos)
# validacionBootstrap.creaParticiones(tic_tac_toe.datos)

Simple Train: [1, 2, 3, 5, 7, 8, 11, 12, 13, 14, 16, 17, 18, 19]
Simple Test: [0, 4, 6, 9, 10, 15]
Cruzada Train: [0, 1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19]
Cruzada Test: [2, 15, 5]
Cruzada Train: [0, 1, 2, 3, 4, 5, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Cruzada Test: [6, 7, 10]
Cruzada Train: [0, 1, 2, 3, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 17, 18]
Cruzada Test: [4, 8, 13, 19]
Cruzada Train: [0, 1, 2, 4, 5, 6, 7, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19]
Cruzada Test: [3, 11, 9]
Cruzada Train: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 19]
Cruzada Test: [0, 14, 18]
Cruzada Train: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 18, 19]
Cruzada Test: [17, 1, 16, 12]
Boostrap Train: [2, 3, 3, 4, 5, 6, 6, 7, 10, 10, 11, 11, 12, 12, 16, 17, 18, 18, 18, 19]
Boostrap Test: [0, 1, 8, 9, 13, 14, 15]


Comentarios sobre las particiones

In [2]:
from ClasificadorNaiveBayes import ClasificadorNaiveBayes
clasificador = ClasificadorNaiveBayes()
errores = clasificador.validacion(validacionCruzada, balloons, clasificador)
print(errores)


[array([False, False, False]) array([False, False, False])
 array([False, False, False, False]) array([False, False, False])
 array([False, False, False]) array([False, False, False, False])
 array([False, False, False]) array([False, False, False])
 array([False, False, False, False]) array([False, False, False])
 array([False, False, False]) array([False, False, False, False])]
